on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    env:
      TESTING: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Update to a valid Python version

      - name: Setup Python Virtual Environment
        run: python -m venv python-virtualenv
      
      - name: Install Dependencies
        run: python-virtualenv/bin/pip install -r requirements.txt  # Correct the path here

      - name: Run Tests
        run: |
          chmod +x run_test.sh
          ./run_test.sh